# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2018-08-06 22:26


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_auto_20180314_0655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abstractelement',
            name='element_type',
            field=models.CharField(choices=[('DATE', 'DATE'), ('ENTRY', 'ENTRY'), ('SELECT', 'SELECT'), ('MULTI_SELECT', 'MULTI_SELECT'), ('RADIO', 'RADIO'), ('PICTURE', 'PICTURE'), ('PLUGIN', 'PLUGIN'), ('ENTRY_PLUGIN', 'ENTRY_PLUGIN')], max_length=12),
        ),
        migrations.AlterField(
            model_name='concept',
            name='data_type',
            field=models.CharField(blank=True, choices=[('string', 'string'), ('boolean', 'boolean'), ('number', 'number'), ('complex', 'complex')], max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='element',
            name='element_type',
            field=models.CharField(choices=[('DATE', 'DATE'), ('ENTRY', 'ENTRY'), ('SELECT', 'SELECT'), ('MULTI_SELECT', 'MULTI_SELECT'), ('RADIO', 'RADIO'), ('PICTURE', 'PICTURE'), ('PLUGIN', 'PLUGIN'), ('ENTRY_PLUGIN', 'ENTRY_PLUGIN')], max_length=12),
        ),
    ]
