# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2019-02-15 22:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_delete_device'),
    ]

    operations = [
        migrations.AddField(
            model_name='abstractelement',
            name='color',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='element',
            name='color',
            field=models.TextField(blank=True, null=True),
        ),
    ]
