# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2019-02-15 23:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_auto_20190215_2206'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='abstractelement',
            name='color',
        ),
        migrations.RemoveField(
            model_name='element',
            name='color',
        ),
    ]
